networks:
  default:
    ipam:
      config:
        - subnet: 10.0.0.0/24

volumes:
  registry:
  debian128:
  debian133:
  ubuntu2204:
  ubuntu2404:
  rockylinux97:
  rockylinux101:
  almalinux101:

services:

  registry:
    image: ghcr.io/project-zot/zot:v2.1.15

    volumes:
      - type: volume
        source: registry
        target: /var/lib/registry

    ports:
      - 5000:5000

    logging:
      driver: local

  ubuntu2204:
    hostname: ubuntu2204
    image: vesselbox/vesselbox

    cap_add:
      - SYS_ADMIN

    profiles:
      - disabled

    environment:
      - SRC_REGISTRY_INSECURE=--insecure
      - SRC_TYPE=registry
      - SRC=registry:5000/vesselbox/ubuntu:22.04

    ports:
      - 20023:22

    volumes:
      - type: volume
        source: ubuntu2204
        target: /data

  ubuntu2404:
    hostname: ubuntu2404
    image: vesselbox/vesselbox

    cap_add:
      - SYS_ADMIN

    profiles:
      - disabled

    environment:
      - SRC_REGISTRY_INSECURE=--insecure
      - SRC_TYPE=registry
      - SRC=registry:5000/vesselbox/ubuntu:24.04

    ports:
      - 20022:22

    volumes:
      - type: volume
        source: ubuntu2404
        target: /data

  debian133:
    hostname: debian133
    image: vesselbox/vesselbox

    cap_add:
      - SYS_ADMIN

    # profiles:
    #   - disabled

    environment:
      - SRC_REGISTRY_INSECURE=--insecure
      - SRC_TYPE=registry
      - SRC=registry:5000/vesselbox/debian:13.3

    ports:
      - 20024:22

    volumes:
      - type: volume
        source: debian133
        target: /data

  debian128:
    hostname: debian128
    image: vesselbox/vesselbox

    cap_add:
      - SYS_ADMIN

    # profiles:
    #   - disabled

    environment:
      - SRC_REGISTRY_INSECURE=--insecure
      - SRC_TYPE=registry
      - SRC=registry:5000/vesselbox/debian:12.8

    ports:
      - 20025:22

    volumes:
      - type: volume
        source: debian128
        target: /data
        
  rockylinux97:
    hostname: rockylinux97
    image: vesselbox/vesselbox

    cap_add:
      - SYS_ADMIN

    environment:
      - SRC_REGISTRY_INSECURE=--insecure
      - SRC_TYPE=registry
      - SRC=registry:5000/vesselbox/rockylinux:9.7
    
    ports:
      - 20026:22

    volumes:
      - type: volume
        source: rockylinux97
        target: /data

  rockylinux101:
    hostname: rockylinux101
    image: vesselbox/vesselbox

    cap_add:
      - SYS_ADMIN

    environment:
      - SRC_REGISTRY_INSECURE=--insecure
      - SRC_TYPE=registry
      - SRC=registry:5000/vesselbox/rockylinux:10.1
    
    ports:
      - 20027:22

    volumes:
      - type: volume
        source: rockylinux101
        target: /data

  almalinux101:
    hostname: almalinux101
    image: vesselbox/vesselbox

    cap_add:
      - SYS_ADMIN

    environment:
      - SRC_REGISTRY_INSECURE=--insecure
      - SRC_TYPE=registry
      - SRC=registry:5000/vesselbox/almalinux:10.1

    # environment:
    #   - container=docker

    ports:
      - 20028:22

    volumes:
      - type: volume
        source: almalinux101
        target: /data
